language : node_js
node_js :
 - stable
install:
 - npm ci
script:
 - npm run test:codecov
before_script:
 - npm run build
deploy:
  provider: npm
  email: "YOUR_EMAIL_ADDRESS"
  api_key: "YOUR_AUTH_TOKEN"
  on:
    tags: true
    branch: master
    skip_cleanup: true