version: 2.1
orbs:
  node: circleci/node@1.1.6

jobs:
  build:
    working_directory: ~/repo
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm ci
            - run: npm run build
            - persist_to_workspace:
                root: ~/repo
                paths: .

  test:
    working_directory: ~/repo
    executor:
      name: node/default
    steps:
      - attach_workspace:
          at: ~/repo
      - run: npm run test:codecov

  deploy:
    working_directory: ~/repo
    executor:
      name: node/default
    steps:
      - attach_workspace:
          at: ~/repo
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run: npm publish

workflows:
    build-and-test:
      jobs:
        - build
        - test:
            requires:
              - build

    build-and-deploy:
      jobs:
        - build
        - test:
            requires:
              - build
        - deploy:
            requires:
              - test
            filters:
              branches:
                only:
                  - master
              tags:
                only: /.*/
