name: Build / Test / Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        path: |
          ~/.npm
          ./node_modules
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
    - name: npm intall, build and test
      run: |
        npm ci
        npm run build --if-present
        npm run test:codecov
        npm run lint
    - name: Save root
      uses: actions/upload-artifact@v2
      with:
          name: root
          path: |
            ${{ github.workspace }}
            !./node_modules
        
        
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        path: |
          ~/.npm
          ./node_modules
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
    - name: Retrieve saved Docker image
      uses: actions/download-artifact@v2
      with:
        name: root
        path: ${{ github.workspace }}
    - name: test
      run: |
        npm run test:codecov
    - name: Post test covarage
      uses: romeovs/lcov-reporter-action@v0.2.16
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        lcov-file: ./coverage/lcov.info
    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
          name: Test results
          path: coverage
        
        
  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        path: |
          ~/.npm
          ./node_modules
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
    - name: Retrieve saved Docker image
      uses: actions/download-artifact@v2
      with:
        name: root
        path: ${{ github.workspace }}
    - name: lint
      run: |
        npm run lint
    

