name: Build / Test / Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      jobs:
        description: 'List of jobs to run'
        required: true
        default: 'build, test, lint'

jobs:
  build:
    if: (!github.event.inputs.jobs || contains(github.event.inputs.jobs, 'build'))
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        path: |
          ~/.npm
          ./node_modules
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
    - name: npm intall, build and test
      run: |
        npm ci
        npm run build --if-present
        npm run test:codecov
        npm run lint
    - name: Save root
      uses: actions/upload-artifact@v2
      with:
          name: root
          path: |
            ${{ github.workspace }}
            !./node_modules
        
        
  test:
    needs: build
    if: (!github.event.inputs.jobs || contains(github.event.inputs.jobs, 'test'))
    runs-on: ubuntu-latest
    steps:
    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        path: |
          ~/.npm
          ./node_modules
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
    - name: Retrieve saved Docker image
      uses: actions/download-artifact@v2
      with:
        name: root
        path: ${{ github.workspace }}
    - name: test
      run: |
        npm run test:codecov
    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
          name: Test results
          path: coverage
        
        
  lint:
    needs: build
    if: (!github.event.inputs.jobs || contains(github.event.inputs.jobs, 'lint'))
    runs-on: ubuntu-latest
    steps:
    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        path: |
          ~/.npm
          ./node_modules
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
    - name: Retrieve saved Docker image
      uses: actions/download-artifact@v2
      with:
        name: root
        path: ${{ github.workspace }}
    - name: lint
      run: |
        npm run lint
    

